export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  originalPrice?: number;
  image: string;
  images?: string[]; // Múltiples imágenes para el showcase 3D
  category: 'juguetes' | 'higiene' | 'alimentacion' | 'descanso' | 'accesorios' | 'acuario' | 'jaulas';
  petType: 'perro' | 'gato' | 'ave' | 'pez' | 'roedor' | 'reptil' | 'todos';
  rating: number;
  reviews: number;
  inStock: boolean;
  cjSku?: string;
  isBundle?: boolean;
  bundleItems?: string[];
  savings?: number;
  has3D?: boolean; // Si tiene secuencia 3D disponible
}

// 🐕 PRODUCTOS PARA PERROS
export const dogProducts: Product[] = [
  {
    id: 'juguete-interactivo-perro',
    name: 'Juguete Interactivo Inteligente',
    description: 'Bola automática con movimiento impredecible. Mantiene a tu perro entretenido por horas. Carga USB, 3 modos de velocidad.',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=400&auto=format&fit=crop',
    category: 'juguetes',
    petType: 'perro',
    rating: 4.8,
    reviews: 127,
    inStock: true,
    cjSku: 'CJDOG001',
    has3D: true,
  },
  {
    id: 'pelota-sonido-perro',
    name: 'Pelota con Sonido Chip-Chip',
    description: 'Pelota resistente con sonido que activa el instinto de caza. Material no tóxico, tamaño perfecto para morder.',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?w=400&auto=format&fit=crop',
    category: 'juguetes',
    petType: 'perro',
    rating: 4.6,
    reviews: 89,
    inStock: true,
    cjSku: 'CJDOG002',
  },
  {
    id: 'cuerda-morder-perro',
    name: 'Cuerda de Algodón Premium',
    description: 'Cuerda trenzada 100% algodón para morder y jalar. Ideal para limpieza dental mientras juega.',
    price: 9.99,
    image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&auto=format&fit=crop',
    category: 'juguetes',
    petType: 'perro',
    rating: 4.7,
    reviews: 156,
    inStock: true,
    cjSku: 'CJDOG003',
  },
  {
    id: 'guante-quitapelos-perro',
    name: 'Guante Quitapelos Mágico',
    description: 'Guante de silicona con 255 pines que remueve pelo suelto mientras acaricias a tu perro. Lavable y reutilizable.',
    price: 18.99,
    image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=400&auto=format&fit=crop',
    category: 'higiene',
    petType: 'perro',
    rating: 4.9,
    reviews: 342,
    inStock: true,
    cjSku: 'CJDOG004',
  },
  {
    id: 'fuente-agua-perro',
    name: 'Fuente de Agua Automática',
    description: 'Fuente de 2.4L con filtro de carbón activado. Flujo continuo que incentiva a tu perro a hidratarse más. Ultra silenciosa.',
    price: 39.99,
    originalPrice: 49.99,
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&auto=format&fit=crop',
    category: 'alimentacion',
    petType: 'perro',
    rating: 4.7,
    reviews: 203,
    inStock: true,
    cjSku: 'CJDOG005',
    has3D: true,
  },
  {
    id: 'comedero-lento-perro',
    name: 'Comedero Slow-Feed',
    description: 'Plato laberinto que reduce la velocidad de alimentación hasta 10x. Previene hinchazón y mejora digestión.',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400&auto=format&fit=crop',
    category: 'alimentacion',
    petType: 'perro',
    rating: 4.8,
    reviews: 178,
    inStock: true,
    cjSku: 'CJDOG006',
  },
  {
    id: 'cama-ortopedica-perro',
    name: 'Cama Ortopédica Memory Foam',
    description: 'Cama ergonómica con espuma viscoelástica. Alivia presión en articulaciones. Funda lavable, base antideslizante.',
    price: 59.99,
    originalPrice: 79.99,
    image: 'https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=400&auto=format&fit=crop',
    category: 'descanso',
    petType: 'perro',
    rating: 4.9,
    reviews: 267,
    inStock: true,
    cjSku: 'CJDOG007',
  },
];

// 🐈 PRODUCTOS PARA GATOS
export const catProducts: Product[] = [
  {
    id: 'rascador-circular-gato',
    name: 'Rascador Circular de Cartón',
    description: 'Rascador duradero con diseño circular que permite a tu gato estirarse y afilar sus uñas. Incluye hierba gatera.',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=400&auto=format&fit=crop',
    category: 'juguetes',
    petType: 'gato',
    rating: 4.8,
    reviews: 234,
    inStock: true,
    cjSku: 'CJCAT001',
  },
  {
    id: 'juguete-pluma-gato',
    name: 'Varita con Plumas Interactiva',
    description: 'Varita extensible con plumas naturales y cascabel. Estimula el instinto de caza. Mango ergonómico antideslizante.',
    price: 8.99,
    image: 'https://images.unsplash.com/photo-1615266895738-11f1371cd7e5?w=400&auto=format&fit=crop',
    category: 'juguetes',
    petType: 'gato',
    rating: 4.7,
    reviews: 189,
    inStock: true,
    cjSku: 'CJCAT002',
  },
  {
    id: 'fuente-agua-gato',
    name: 'Fuente Flor de Agua para Gatos',
    description: 'Diseño de flor con 3 modos de flujo. Super silenciosa (<30dB). Filtro de carbón activado remueve pelo e impurezas.',
    price: 29.99,
    originalPrice: 39.99,
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&auto=format&fit=crop',
    category: 'alimentacion',
    petType: 'gato',
    rating: 4.9,
    reviews: 445,
    inStock: true,
    cjSku: 'CJCAT003',
    has3D: true,
  },
  {
    id: 'cama-ventana-gato',
    name: 'Hamaca de Ventana para Gatos',
    description: 'Cama con ventosas de alta resistencia (hasta 15kg). Felpa suave y cómoda. Perfecta para gatos que aman el sol.',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1513245543132-31f507417b26?w=400&auto=format&fit=crop',
    category: 'descanso',
    petType: 'gato',
    rating: 4.8,
    reviews: 312,
    inStock: true,
    cjSku: 'CJCAT004',
  },
  {
    id: 'arena-autolimpiable',
    name: 'Arenero Autolimpiable Eléctrico',
    description: 'Arenero inteligente que detecta cuando tu gato sale y limpia automáticamente. Control por app. Elimina olores al instante.',
    price: 399.99,
    originalPrice: 499.99,
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&auto=format&fit=crop',
    category: 'higiene',
    petType: 'gato',
    rating: 4.6,
    reviews: 89,
    inStock: true,
    cjSku: 'CJCAT005',
    has3D: true,
  },
  {
    id: 'cepillo-silicona-gato',
    name: 'Cepillo de Silicona para Gatos',
    description: 'Cepillo suave que imita la lengua de un gato. Masaje relajante mientras remueve pelo suelto. Se pega a cualquier esquina.',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1513245543132-31f507417b26?w=400&auto=format&fit=crop',
    category: 'higiene',
    petType: 'gato',
    rating: 4.5,
    reviews: 167,
    inStock: true,
    cjSku: 'CJCAT006',
  },
  {
    id: 'torre-rascador-gato',
    name: 'Torre Rascador 3 Niveles',
    description: 'Árbol para gatos con postes de sisal, plataformas acolchadas y cueva escondite. Altura: 110cm. Base estable.',
    price: 79.99,
    originalPrice: 99.99,
    image: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=400&auto=format&fit=crop',
    category: 'descanso',
    petType: 'gato',
    rating: 4.7,
    reviews: 123,
    inStock: true,
    cjSku: 'CJCAT007',
  },
];

// 🦜 PRODUCTOS PARA AVES
export const birdProducts: Product[] = [
  {
    id: 'jaula-loro-deluxe',
    name: 'Jaula Deluxe para Loros',
    description: 'Jaula espaciosa de 120cm con 3 puertas, bandejas extraíbles y perchas de madera natural. Incluye comederos de acero inoxidable.',
    price: 149.99,
    originalPrice: 189.99,
    image: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400&auto=format&fit=crop',
    category: 'jaulas',
    petType: 'ave',
    rating: 4.8,
    reviews: 67,
    inStock: true,
    cjSku: 'CJBIRD001',
    has3D: true,
  },
  {
    id: 'juguete-masticable-ave',
    name: 'Juguete Masticable Natural',
    description: 'Juguete de madera, yute y cuero para mantener el pico saludable. Colores vibrantes no tóxicos.',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400&auto=format&fit=crop',
    category: 'juguetes',
    petType: 'ave',
    rating: 4.6,
    reviews: 45,
    inStock: true,
    cjSku: 'CJBIRD002',
  },
  {
    id: 'comedero-automatico-ave',
    name: 'Comedero Automático Inteligente',
    description: 'Dispensador programable con 6 compartimentos. Control por app. Ideal para cuando estás de viaje.',
    price: 59.99,
    image: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400&auto=format&fit=crop',
    category: 'alimentacion',
    petType: 'ave',
    rating: 4.7,
    reviews: 89,
    inStock: true,
    cjSku: 'CJBIRD003',
  },
  {
    id: 'baño-ave',
    name: 'Bañera de Lujo para Aves',
    description: 'Bañera con espejo y perchita. Se cuelga en la jaula fácilmente. Fácil de limpiar y recargar.',
    price: 11.99,
    image: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400&auto=format&fit=crop',
    category: 'higiene',
    petType: 'ave',
    rating: 4.5,
    reviews: 34,
    inStock: true,
    cjSku: 'CJBIRD004',
  },
  {
    id: 'columpio-ave',
    name: 'Columpio con Campana',
    description: 'Columpio de madera natural con campana musical. Estimula el ejercicio y el entretenimiento.',
    price: 8.99,
    image: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400&auto=format&fit=crop',
    category: 'juguetes',
    petType: 'ave',
    rating: 4.4,
    reviews: 56,
    inStock: true,
    cjSku: 'CJBIRD005',
  },
];

// 🐹 PRODUCTOS PARA ROEDORES (hámsters, conejos, cobayas)
export const rodentProducts: Product[] = [
  {
    id: 'jaula-hamster-deluxe',
    name: 'Habitat Deluxe para Hámsters',
    description: 'Jaula de 3 niveles con túneles, rueda de ejercicio, casa escondite y comederos. Incluye base extraíble para limpieza.',
    price: 69.99,
    originalPrice: 89.99,
    image: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=400&auto=format&fit=crop',
    category: 'jaulas',
    petType: 'roedor',
    rating: 4.7,
    reviews: 234,
    inStock: true,
    cjSku: 'CJROD001',
  },
  {
    id: 'rueda-ejercicio-silenciosa',
    name: 'Rueda de Ejercicio Silenciosa',
    description: 'Rueda de 21cm con rodamiento de bolas ultra silencioso. Superficie texturizada antideslizante.',
    price: 18.99,
    image: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=400&auto=format&fit=crop',
    category: 'juguetes',
    petType: 'roedor',
    rating: 4.8,
    reviews: 445,
    inStock: true,
    cjSku: 'CJROD002',
  },
  {
    id: 'bebbedero-automatico-roedor',
    name: 'Bebedero Automático con Soporte',
    description: 'Bebedero de 125ml con boquilla de acero inoxidable y soporte ajustable. No gotea.',
    price: 9.99,
    image: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=400&auto=format&fit=crop',
    category: 'alimentacion',
    petType: 'roedor',
    rating: 4.6,
    reviews: 178,
    inStock: true,
    cjSku: 'CJROD003',
  },
  {
    id: 'casa-madera-conejo',
    name: 'Casa de Madera para Conejos',
    description: 'Casita espaciosa de madera natural no tratada. Dos entradas para escapar fácilmente. Ideal para conejos y cobayas.',
    price: 34.99,
    image: 'https://images.unsplash.com/photo-1585110396063-8355845b29e7?w=400&auto=format&fit=crop',
    category: 'descanso',
    petType: 'roedor',
    rating: 4.7,
    reviews: 89,
    inStock: true,
    cjSku: 'CJROD004',
  },
  {
    id: 'tunel-extensible-hamster',
    name: 'Túnel Extensible de Plástico',
    description: 'Sistema de túneles modulares que se conectan entre sí. Compatible con la mayoría de jaulas.',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=400&auto=format&fit=crop',
    category: 'juguetes',
    petType: 'roedor',
    rating: 4.5,
    reviews: 123,
    inStock: true,
    cjSku: 'CJROD005',
  },
];

// 🐠 PRODUCTOS PARA PECES
export const fishProducts: Product[] = [
  {
    id: 'acuario-completo-20l',
    name: 'Acuario Completo 20 Litros',
    description: 'Kit todo incluido: acuario de cristal, filtro interno, iluminación LED, termómetro y red. Incluye guía de inicio.',
    price: 89.99,
    originalPrice: 119.99,
    image: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=400&auto=format&fit=crop',
    category: 'acuario',
    petType: 'pez',
    rating: 4.8,
    reviews: 156,
    inStock: true,
    cjSku: 'CJFISH001',
    has3D: true,
  },
  {
    id: 'filtro-externo-acuario',
    name: 'Filtro Externo Canister Pro',
    description: 'Filtro de alto rendimiento para acuarios hasta 100L. 3 etapas de filtración. Flujo ajustable hasta 400L/h.',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=400&auto=format&fit=crop',
    category: 'acuario',
    petType: 'pez',
    rating: 4.7,
    reviews: 89,
    inStock: true,
    cjSku: 'CJFISH002',
  },
  {
    id: 'iluminacion-led-acuario',
    name: 'Lámpara LED RGB para Acuario',
    description: 'Iluminación LED multicolor con control remoto. Simulación amanecer/atardecer. Ahorra hasta 80% de energía.',
    price: 34.99,
    originalPrice: 44.99,
    image: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=400&auto=format&fit=crop',
    category: 'acuario',
    petType: 'pez',
    rating: 4.6,
    reviews: 67,
    inStock: true,
    cjSku: 'CJFISH003',
  },
  {
    id: 'calentador-sumergible',
    name: 'Calentador Sumergible 50W',
    description: 'Termostato ajustable 20-34°C. Mantiene temperatura estable. Protección contra sobrecalentamiento.',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=400&auto=format&fit=crop',
    category: 'acuario',
    petType: 'pez',
    rating: 4.5,
    reviews: 234,
    inStock: true,
    cjSku: 'CJFISH004',
  },
  {
    id: 'decoracion-acuario',
    name: 'Set Decoración Natural',
    description: 'Piedras de río, troncos driftwood y plantas artificiales realistas. Seguro para todos los peces.',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=400&auto=format&fit=crop',
    category: 'acuario',
    petType: 'pez',
    rating: 4.4,
    reviews: 45,
    inStock: true,
    cjSku: 'CJFISH005',
  },
];

// 🦎 PRODUCTOS PARA REPTILES
export const reptileProducts: Product[] = [
  {
    id: 'terrario-completo',
    name: 'Terrario de Cristal 60x40x40cm',
    description: 'Terrario de vidrio templado con tapa de malla. Puertas corredizas frontales. Ideal para geckos, serpientes pequeñas y lagartos.',
    price: 129.99,
    originalPrice: 159.99,
    image: 'https://images.unsplash.com/photo-1504450874802-0ed58ffa57b7?w=400&auto=format&fit=crop',
    category: 'accesorios',
    petType: 'reptil',
    rating: 4.7,
    reviews: 56,
    inStock: true,
    cjSku: 'CJREP001',
    has3D: true,
  },
  {
    id: 'lampara-calefactora',
    name: 'Lámpara Calefactora UVA/UVB',
    description: 'Bombilla todo-en-uno que proporciona calor, luz UVA y UVB esencial para la salud ósea de reptiles.',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1504450874802-0ed58ffa57b7?w=400&auto=format&fit=crop',
    category: 'accesorios',
    petType: 'reptil',
    rating: 4.8,
    reviews: 123,
    inStock: true,
    cjSku: 'CJREP002',
  },
  {
    id: 'sustrato-coco',
    name: 'Sustrato de Fibra de Coco 10L',
    description: 'Sustrato 100% natural que retiene humedad. Ideal para terrarios tropicales. Comprimido expande 10L.',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1504450874802-0ed58ffa57b7?w=400&auto=format&fit=crop',
    category: 'accesorios',
    petType: 'reptil',
    rating: 4.6,
    reviews: 89,
    inStock: true,
    cjSku: 'CJREP003',
  },
  {
    id: 'cueva-reptil',
    name: 'Cueva de Resina Grande',
    description: 'Escondite realista con dos entradas. Superficie texturizada para ayudar a la muda. Fácil de limpiar.',
    price: 22.99,
    image: 'https://images.unsplash.com/photo-1504450874802-0ed58ffa57b7?w=400&auto=format&fit=crop',
    category: 'descanso',
    petType: 'reptil',
    rating: 4.5,
    reviews: 67,
    inStock: true,
    cjSku: 'CJREP004',
  },
];

// 🎁 BUNDLES MULTI-MASCOTA
export const bundles: Product[] = [
  {
    id: 'pack-gato-starter',
    name: 'Kit Bienvenida Gatuno',
    description: 'Todo lo que necesita tu nuevo gatito: rascador, varita interactiva, cepillo y fuente de agua.',
    price: 59.99,
    originalPrice: 76.96,
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&auto=format&fit=crop',
    category: 'juguetes',
    petType: 'gato',
    rating: 4.9,
    reviews: 178,
    inStock: true,
    isBundle: true,
    bundleItems: ['rascador-circular-gato', 'juguete-pluma-gato', 'cepillo-silicona-gato'],
    savings: 16.97,
    cjSku: 'CJPACKCAT001',
  },
  {
    id: 'pack-hamster-completo',
    name: 'Habitat Completo Hámster',
    description: 'Jaula grande + rueda silenciosa + túneles + bebedero. Todo para que tu hámster sea feliz.',
    price: 89.99,
    originalPrice: 114.96,
    image: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=400&auto=format&fit=crop',
    category: 'jaulas',
    petType: 'roedor',
    rating: 4.8,
    reviews: 234,
    inStock: true,
    isBundle: true,
    bundleItems: ['jaula-hamster-deluxe', 'rueda-ejercicio-silenciosa', 'tunel-extensible-hamster'],
    savings: 24.97,
    cjSku: 'CJPACKROD001',
  },
  {
    id: 'pack-acuario-starter',
    name: 'Kit Acuario Principiante',
    description: 'Acuario 20L completo con filtro extra, LED RGB y decoración. Todo para empezar tu primer acuario.',
    price: 129.99,
    originalPrice: 164.97,
    image: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=400&auto=format&fit=crop',
    category: 'acuario',
    petType: 'pez',
    rating: 4.9,
    reviews: 89,
    inStock: true,
    isBundle: true,
    bundleItems: ['acuario-completo-20l', 'iluminacion-led-acuario', 'decoracion-acuario'],
    savings: 34.98,
    cjSku: 'CJPACKFISH001',
  },
  {
    id: 'pack-perro-premium',
    name: 'Pack Premium Canino',
    description: 'Lo mejor para tu perro: juguete interactivo, guante quitapelos, fuente de agua y cama ortopédica.',
    price: 119.99,
    originalPrice: 144.96,
    image: 'https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=400&auto=format&fit=crop',
    category: 'juguetes',
    petType: 'perro',
    rating: 4.9,
    reviews: 156,
    inStock: true,
    isBundle: true,
    bundleItems: ['juguete-interactivo-perro', 'guante-quitapelos-perro', 'fuente-agua-perro'],
    savings: 24.97,
    cjSku: 'CJPACKDOG001',
  },
  {
    id: 'pack-multi-mascota',
    name: 'Super Pack Familia de Mascotas',
    description: '¿Tienes varias mascotas? Este pack incluye regalos para perros, gatos y roedores. El kit familiar definitivo.',
    price: 199.99,
    originalPrice: 259.95,
    image: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&auto=format&fit=crop',
    category: 'juguetes',
    petType: 'todos',
    rating: 5.0,
    reviews: 67,
    inStock: true,
    isBundle: true,
    bundleItems: ['pelota-sonido-perro', 'rascador-circular-gato', 'rueda-ejercicio-silenciosa'],
    savings: 59.96,
    cjSku: 'CJPACKALL001',
  },
];

// Combina todos los productos
export const allProducts = [
  ...dogProducts,
  ...catProducts,
  ...birdProducts,
  ...rodentProducts,
  ...fishProducts,
  ...reptileProducts,
  ...bundles,
];

// Productos individuales (sin bundles) para ciertas vistas
export const individualProducts = [
  ...dogProducts,
  ...catProducts,
  ...birdProducts,
  ...rodentProducts,
  ...fishProducts,
  ...reptileProducts,
];

// Funciones helper
export function getProductById(id: string): Product | undefined {
  return allProducts.find(p => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return individualProducts.filter(p => p.category === category);
}

export function getProductsByPetType(petType: string): Product[] {
  if (petType === 'todos') return individualProducts;
  return individualProducts.filter(p => p.petType === petType || p.petType === 'todos');
}

export function qualifiesForFreeShipping(cartTotal: number): boolean {
  return cartTotal >= 35;
}

export function calculateShipping(cartTotal: number): number {
  return qualifiesForFreeShipping(cartTotal) ? 0 : 5.99;
}

// Pet type info para la UI
export const petTypes = [
  { id: 'todos', name: 'Todos', emoji: '🐾', color: 'bg-gray-500' },
  { id: 'perro', name: 'Perros', emoji: '🐕', color: 'bg-orange-500' },
  { id: 'gato', name: 'Gatos', emoji: '🐈', color: 'bg-blue-500' },
  { id: 'ave', name: 'Aves', emoji: '🦜', color: 'bg-yellow-500' },
  { id: 'pez', name: 'Peces', emoji: '🐠', color: 'bg-cyan-500' },
  { id: 'roedor', name: 'Roedores', emoji: '🐹', color: 'bg-pink-500' },
  { id: 'reptil', name: 'Reptiles', emoji: '🦎', color: 'bg-green-600' },
];
